org.gradle.jvmargs=-Xmx3g
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# FIXME https://github.com/modrinth/minotaur/issues/75
org.gradle.configuration-cache=false
org.gradle.logging.level=info

java_version=21
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.174
neo_version_range=[21.1.174,)
neogradle_version=7+
loader_version_range=[2,)
pack_format_number=18

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

sonar_version=5.1+
sonar.gradle.skipCompile=true

release_type=alpha
release_versions=1.21.1

dpanvil_version=6.1.0
