modLoader="javafml"
loaderVersion="[39,)"
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="dpanvil"
version="${file.jarVersion}"
displayName="DataPack Anvil"
description='''A library mod to create datapack driven mods.'''

[[dependencies.dpanvil]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.5,)"
    ordering="NONE"
    side="BOTH"

    [[dependencies.dpanvil]]
    modId="jei"
    mandatory=false
    versionRange="[FORGE-1.18.1-9.1.0.46,)"
    ordering="AFTER"
    side="BOTH"
