modLoader="javafml"
loaderVersion="[40,)"
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="dpanvil"
version="${file.jarVersion}"
displayName="DataPack Anvil"
description='''A library mod to create datapack driven mods.'''

[[dependencies.dpanvil]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.19,)"
    ordering="NONE"
    side="BOTH"

    [[dependencies.dpanvil]]
    modId="jei"
    mandatory=false
    versionRange="[FORGE-1.18.2-9.2.1.69,)"
    ordering="AFTER"
    side="BOTH"
