modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="dpanvil"
version="${dpanvil_version}"
displayName="DataPack Anvil"
description='''A library mod to create datapack driven mods.'''

[[dependencies.dpanvil]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.dpanvil]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
