modLoader="javafml"
loaderVersion="[40,)"
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="dpanvil"
version="${file.jarVersion}"
displayName="DataPack Anvil"
description='''A library mod to create datapack driven mods.'''

[[dependencies.dpanvil]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.30,)"
    ordering="NONE"
    side="BOTH"
