modLoader="javafml"
loaderVersion="[43,)"
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="dpanvil"
version="${file.jarVersion}"
displayName="DataPack Anvil"
description='''A library mod to create datapack driven mods.'''

[[dependencies.dpanvil]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.3,)"
    ordering="NONE"
    side="BOTH"
