modLoader="javafml"
loaderVersion="[38,)"
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="dpanvil"
version="${file.jarVersion}"
displayName="DataPack Anvil"
description='''A library mod to create datapack driven mods.'''

[[dependencies.dpanvil]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.14,)"
    ordering="NONE"
    side="BOTH"

    [[dependencies.dpanvil]]
    modId="jei"
    mandatory=false
    versionRange="[FORGE-1.18-9.0.0.40,)"
    ordering="AFTER"
    side="BOTH"
